Repository WePlanPlans/WPP_FE, pull requests merged in 2024-01, with the labels that each got.

#18 Feat: 인기 여행지 기능 구현
  index.html
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/@types/detail.types.ts
  src/@types/tours.types.ts
  src/App.css
  src/App.tsx
  src/api/region.ts
  src/api/tours.ts
  src/assets/images/Star.svg
  src/components/DetailSectionBottom/DetailReview.tsx
  src/components/DetailSectionBottom/DetailReviewStats.tsx
  src/components/DetailSectionBottom/DetailSectionBottom.tsx
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/DetailSectionBottom/index.tsx
  src/components/DetailSectionTop/DetailSectionTop.tsx
  src/components/DetailSectionTop/DetailTourButtons.tsx
  src/components/DetailSectionTop/DetailToursInfo.tsx
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/components/DetailSectionTop/DetailToursRating.tsx
  src/components/DetailSectionTop/DetailToutsMap.tsx
  src/components/DetailSectionTop/index.tsx
  src/components/Review/Review.tsx
  src/components/Review/ReviewButton.tsx
  src/components/Review/ReviewKeyword.tsx
  src/components/Review/ReviewPosting.tsx
  src/components/Review/ReviewRating.tsx
  src/components/Review/index.tsx
  src/components/Tours/ToursCategory.tsx
  src/components/Tours/ToursCategoryItem.tsx
  src/components/Tours/ToursItem.tsx
  src/components/Tours/ToursList.tsx
  src/components/Tours/ToursSectionTop.tsx
  src/components/abc/A.tsx
  src/components/abc/B.tsx
  src/components/abc/index.tsx
  src/components/common/footer/index.tsx
  src/components/common/header/ReviewHeader.tsx
  src/components/common/header/index.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/nav/Nav.tsx
  src/components/common/nav/index.tsx
  src/components/def/C.tsx
  src/components/def/D.tsx
  src/components/def/index.tsx
  src/hooks/abc.ts
  src/hooks/useReviewStats.ts
  src/hooks/useReviewStatsCalculator.ts
  src/index.css
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/abc/abc.page.tsx
  src/pages/detail/detail.page.tsx
  src/pages/main/main.page.tsx
  src/pages/postingReview/postingReview.page.tsx
  src/router/mainRouter.tsx
  src/utils/abc.ts
  src/utils/utils.ts
Labels: ✨ Feature

#15 Feat: 상세 페이지 기능 구현 완료
  index.html
  src/assets/images/Star.svg
  src/components/DetailSectionTop/DetailSectionTop.tsx
  src/components/DetailSectionTop/DetailToursButtons.tsx
  src/components/DetailSectionTop/DetailToursInfo.tsx
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/components/DetailSectionTop/DetailToursRating.tsx
  src/components/DetailSectionTop/DetailToutsMap.tsx
  src/main.tsx
  src/pages/detail/detail.page.tsx
  tsconfig.json
Labels: ✨ Feature

#23 Env: 배포오류수정
  package.json
  pnpm-lock.yaml
  src/components/DetailSectionBottom/DetailReview.tsx
  src/components/DetailSectionBottom/DetailSectionBottom.tsx
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/DetailSectionBottom/index.tsx
  src/components/Review/ReviewRating.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
Labels: 🌏 Depoly

#25 Deploy: preview 설정
  .github/workflows/preview.yaml
  .github/workflows/production.yaml
Labels: 🌏 Depoly

#43 Preview Test
  .github/workflows/preview.yaml
  .github/workflows/production.yaml
  README.md
Labels: 🌏 Depoly

#48 Feat: 인기여행지 무한스크롤
  .github/workflows/preview.yaml
  README.md
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/DetailSectionBottom/DetailReview.tsx
  src/components/DetailSectionBottom/DetailReviewStats.tsx
  src/components/DetailSectionBottom/DetailSectionBottom.tsx
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/DetailSectionBottom/index.tsx
  src/components/DetailSectionTop/DetailSectionTop.tsx
  src/components/DetailSectionTop/DetailToursButtons.tsx
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/components/DetailSectionTop/index.tsx
  src/components/Review/ReviewRating.tsx
  src/components/Tours/ToursItem.tsx
  src/components/Tours/ToursList.tsx
  src/index.css
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/detail/detail.page.tsx
  src/router/mainRouter.tsx
  tailwind.config.js
Labels: ✨ Feature

#53 여정생성 버튼 마크업
  src/components/Tours/CreateTripButton.tsx
  src/components/Tours/ToursSectionTop.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/nav/Nav.tsx
  src/pages/main/main.page.tsx
Labels: 🎨 Publishing

#52 검색기능 구현
  package.json
  pnpm-lock.yaml
  src/@types/tours.types.ts
  src/api/tours.ts
  src/assets/images/DeleteInput.svg
  src/assets/images/Search.svg
  src/components/common/spinner/Spinner.tsx
  src/components/common/toggleGroup/ToggleValue.tsx
  src/components/search/RegionSelect.tsx
  src/components/search/ResultCategory.tsx
  src/components/search/ResultItem.tsx
  src/components/search/SearchInput.tsx
  src/components/search/SearchResult.tsx
  src/components/search/StartSearchBtn.tsx
  src/constants.ts
  src/hooks/useDebounce.ts
  src/pages/main/main.page.tsx
  src/pages/search/search.page.tsx
  src/router/mainRouter.tsx
Labels: ✨ Feature

#54 Feat: 인기여행지 구현
  README.md
  package.json
  src/api/comments.ts
  src/api/member.ts
  src/api/review.ts
  src/api/tours.ts
  src/components/DetailSectionBottom/DetailReview.tsx
  src/components/DetailSectionBottom/DetailSectionBottom.tsx
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/DetailSectionBottom/index.tsx
  src/components/DetailSectionTop/DetailSectionTop.tsx
  src/components/DetailSectionTop/DetailToursButtons.tsx
  src/components/Review/CommentItem.tsx
  src/components/Review/DetailReview.tsx
  src/components/Review/InputComment.tsx
  src/components/Review/Review.tsx
  src/components/Review/ReviewButton.tsx
  src/components/Review/ReviewComments.tsx
  src/components/Review/ReviewKeyword.tsx
  src/components/Review/ReviewPosting.tsx
  src/components/Review/ReviewRating.tsx
  src/components/Review/index.tsx
  src/components/Tours/CreateTripButton.tsx
  src/components/Tours/ToursItem.tsx
  src/components/Tours/ToursList.tsx
  src/components/Tours/ToursSectionTop.tsx
  src/components/common/button/Button.tsx
  src/components/common/footer/Footer.tsx
  src/components/common/footer/index.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/index.tsx
  src/components/common/nav/Nav.tsx
  src/pages/main/main.page.tsx
  src/pages/postingReview/postingReview.page.tsx
  src/pages/reviewComment/reviewComment.page.tsx
  src/recoil/abc.ts
  src/recoil/modal.ts
  src/recoil/review.ts
  src/router/mainRouter.tsx
  tailwind.config.js
Labels: ✨ Feature

#64 Env: vercel.json 추가
  vercel.json
Labels: 👾 Fix

#65 Feat: 파비콘 변경, 로그인 레이아웃 조정
  index.html
  public/favicon.jpeg
  public/favicon.svg
  src/components/common/nav/Nav.tsx
  src/pages/signin/signin.page.tsx
  src/pages/signup/signup.page.tsx
  src/router/mainRouter.tsx
Labels: 🌏 Deploy

#66 여정생성 버튼 UI 수정
  src/components/Tours/CreateTripButton.tsx
  src/components/common/footer/Footer.tsx
  src/components/common/footer/index.tsx
Labels: 🎨 Publishing

#67 Feat: 인기 지역 카테고리 swiper 적용
  package.json
  pnpm-lock.yaml
  src/components/Tours/ToursCategory.tsx
  src/components/Tours/ToursCategoryItem.tsx
  src/components/Tours/ToursSectionTop.tsx
Labels: ✨ Feature

#70 Feat: 인기여행지 스켈레톤 적용
  src/components/Tours/ToursCategory.tsx
  src/components/Tours/ToursCategoryItemSkeleton.tsx
  src/components/Tours/ToursItemSkeleton.tsx
  src/components/Tours/ToursList.tsx
  src/components/common/nav/Nav.tsx
Labels: ✨ Feature

#69 검색기능 QA 대응
  index.html
  src/components/search/RegionSelect.tsx
  src/components/search/ResultCategory.tsx
  src/components/search/SearchInput.tsx
  src/components/search/SearchResult.tsx
  src/pages/search/search.page.tsx
Labels: 👾 Fix

#72 상세페이지 QA 보완
  package-lock.json
  package.json
  src/api/tours.ts
  src/components/DetailSectionBottom/DetailReviews.tsx
  src/components/DetailSectionTop/DetailToursInfo.tsx
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/components/DetailSectionTop/DetailToursRating.tsx
  src/components/DetailSectionTop/index.tsx
  src/components/common/icons/Icons.tsx
Labels: ✨ Feature

#76 Refator : 1차 QA 반영
  index.html
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/tours.ts
  src/components/DetailSectionBottom/DetailReviews.tsx
  src/components/DetailSectionTop/DetailSectionTop.tsx
  src/components/DetailSectionTop/DetailToursInfo.tsx
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/components/DetailSectionTop/DetailToursRating.tsx
  src/components/DetailSectionTop/index.tsx
  src/components/common/icons/Icons.tsx
  src/components/search/RegionSelect.tsx
  src/components/search/ResultCategory.tsx
  src/components/search/SearchInput.tsx
  src/components/search/SearchResult.tsx
  src/pages/search/search.page.tsx
  src/router/authRouter.tsx
  src/router/mainRouter.tsx
  src/router/routerLayout.tsx
Labels: 🛠️ Refactor

#77 Refactor: 인기 여행지 스켈레톤 수정
  index.html
  src/App.tsx
  src/components/Tours/ToursCategory.tsx
  src/components/Tours/ToursList.tsx
  src/components/Tours/ToursSectionTop.tsx
  src/components/common/nav/Nav.tsx
  src/router/ScrollToTop.ts
  src/router/authRouter.tsx
  src/router/mainRouter.tsx
  src/router/routerLayout.tsx
Labels: 🛠️ Refactor

#79 리뷰/댓글 1차 QA 반영
  src/api/review.ts
  src/api/tours.ts
  src/components/DetailSectionBottom/DetailReviewStats.tsx
  src/components/DetailSectionBottom/DetailReviews.tsx
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/DetailSectionTop/DetailSectionTop.tsx
  src/components/Review/CommentItem.tsx
  src/components/Review/DetailReview.tsx
  src/components/Review/InputComment.tsx
  src/components/Review/Review.tsx
  src/components/Review/ReviewComments.tsx
  src/components/Review/ReviewKeyword.tsx
  src/components/Review/ReviewPosting.tsx
  src/components/Review/index.tsx
  src/components/common/header/DetailHeader.tsx
  src/components/common/header/ReviewHeader.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/nav/InputComment.tsx
  src/components/common/nav/index.tsx
  src/hooks/useReviewStats.ts
  src/pages/reviewComment/reviewComment.page.tsx
  src/router/mainRouter.tsx
  src/router/routerLayout.tsx
  src/utils/getStarFill.ts
  tailwind.config.js
Labels: 🛠️ Refactor

#82 안기여행지 QA
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/Tours/CreateTripButton.tsx
  src/components/Tours/ToursCategory.tsx
  src/components/Tours/ToursCategoryItem.tsx
  src/components/Tours/ToursCategoryItemSkeleton.tsx
  src/components/Tours/ToursItemSkeleton.tsx
  src/components/Tours/ToursList.tsx
  src/components/Tours/ToursSectionTop.tsx
  src/components/common/footer/Footer.tsx
  src/components/common/footer/index.tsx
  src/components/common/nav/Nav.tsx
  src/router/ScrollToTop.ts
  src/router/authRouter.tsx
  src/router/mainRouter.tsx
Labels: 🛠️ Refactor

#83 인기여행지 QA
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/Tours/CreateTripButton.tsx
  src/components/Tours/ToursCategory.tsx
  src/components/Tours/ToursCategoryItem.tsx
  src/components/Tours/ToursCategoryItemSkeleton.tsx
  src/components/Tours/ToursItemSkeleton.tsx
  src/components/Tours/ToursList.tsx
  src/components/Tours/ToursSectionTop.tsx
  src/components/common/footer/Footer.tsx
  src/components/common/footer/index.tsx
  src/components/common/nav/Nav.tsx
  src/router/ScrollToTop.ts
  src/router/authRouter.tsx
  src/router/mainRouter.tsx
Labels: 🛠️ Refactor

#84 인기여행지 좋아요 기능
  src/@types/detail.types.ts
  src/components/DetailSectionTop/DetailToursInfo.tsx
  src/components/Tours/ToursCategory.tsx
  src/components/Tours/ToursItem.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/like/Like.tsx
Labels: ✨ Feature

#86 인기여행지 좋아요 기능 추가
  src/@types/detail.types.ts
  src/components/DetailSectionTop/DetailToursInfo.tsx
  src/components/Tours/ToursCategory.tsx
  src/components/Tours/ToursItem.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/like/Like.tsx
Labels: ✨ Feature

#89 리뷰/댓글 2차 QA 반영
  package.json
  pnpm-lock.yaml
  src/assets/images/CircleCheck.svg
  src/components/DetailSectionBottom/DetailReviews.tsx
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/Review/CommentItem.tsx
  src/components/Review/Review.tsx
  src/components/Review/ReviewButton.tsx
  src/components/Review/ReviewComments.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/button/Button.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/children/DeleteAlert.tsx
  src/components/common/modal/children/EditDelete.tsx
  src/components/common/nav/InputComment.tsx
  src/recoil/modal.ts
  src/recoil/review.ts
Labels: 👾 Fix

#87 Feat: 일정 추가하기 퍼블리싱완료, Alert 공통 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/api/trips.ts
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/DetailSectionTop/DetailToursButtons.tsx
  src/components/common/alert/Alert.tsx
Labels: ✨ Feature

#92 Feat: 일정 추가하기 퍼블리싱완료, Alert 공통 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/api/trips.ts
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/DetailSectionTop/DetailToursButtons.tsx
  src/components/common/alert/Alert.tsx
Labels: 🌏 Deploy

#98 Feat: 마이페이지/나의관심여행지 구현 완료
  src/@types/tours.types.ts
  src/api/member.ts
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/components/Wish/Wish.tsx
  src/components/Wish/WishCategory.tsx
  src/components/Wish/WishCategoryItem.tsx
  src/components/Wish/WishItem.tsx
  src/components/Wish/WishList.tsx
  src/components/common/like/Like.tsx
  src/components/common/nav/Nav.tsx
  src/pages/wishList/wishList.page.tsx
  src/router/mainRouter.tsx
Labels: ✨ Feature

#99 Feat : 마이페이지/나의관심여행지 기능 구현
  src/@types/tours.types.ts
  src/api/client.ts
  src/api/member.ts
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/components/Wish/Wish.tsx
  src/components/Wish/WishCategory.tsx
  src/components/Wish/WishCategoryItem.tsx
  src/components/Wish/WishItem.tsx
  src/components/Wish/WishList.tsx
  src/components/common/like/Like.tsx
  src/components/common/nav/Nav.tsx
  src/pages/wishList/wishList.page.tsx
  src/router/mainRouter.tsx
Labels: ✨ Feature

#100 Feat : 마이페이지/나의관심여행지 기능 구현
  src/@types/tours.types.ts
  src/api/client.ts
  src/api/member.ts
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/components/Wish/Wish.tsx
  src/components/Wish/WishCategory.tsx
  src/components/Wish/WishCategoryItem.tsx
  src/components/Wish/WishItem.tsx
  src/components/Wish/WishList.tsx
  src/components/common/like/Like.tsx
  src/components/common/nav/Nav.tsx
  src/pages/wishList/wishList.page.tsx
  src/router/mainRouter.tsx
Labels: ✨ Feature

#105 Fe 49 feat/review comment qa
  src/components/DetailSectionBottom/DetailReviews.tsx
  src/components/DetailSectionTop/DetailToursButtons.tsx
  src/components/common/button/Button.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/children/DeleteAlert.tsx
  src/components/common/modal/children/EditDelete.tsx
  src/components/common/nav/InputComment.tsx
  src/components/common/toastpopup/ToastPopUp.tsx
Labels: 👾 Fix

#109 Fe 49 feat/review comment qa
  src/components/DetailSectionBottom/ReviewItem.tsx
Labels: 👾 Fix

#101 Feat: 아코디언 공통컴포넌트 구현, 이런점이 좋았어요 count 레이아웃 리펙토링, 여정 API 추가
  package.json
  pnpm-lock.yaml
  src/api/trips.ts
  src/components/DetailSectionBottom/DetailReviewStats.tsx
  src/components/common/accordion/Accordion.tsx
  src/components/common/icons/Icons.tsx
  src/index.css
Labels: ✨ Feature, 📬 API, 🛠️ Refactor

#106 리뷰/댓글 3차 QA 반영
  package.json
  pnpm-lock.yaml
  src/api/trips.ts
  src/components/DetailSectionBottom/DetailReviewStats.tsx
  src/components/DetailSectionBottom/DetailReviews.tsx
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/DetailSectionTop/DetailToursButtons.tsx
  src/components/common/accordion/Accordion.tsx
  src/components/common/button/Button.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/children/DeleteAlert.tsx
  src/components/common/modal/children/EditDelete.tsx
  src/components/common/nav/InputComment.tsx
  src/components/common/toastpopup/ToastPopUp.tsx
  src/index.css
Labels: 👾 Fix

#110 Feat: 마이관심여행지 데이터 없을시 컴포넌트
  src/components/Wish/Wish.tsx
  src/components/common/noData/NoDataMessage.tsx
Labels: ✨ Feature

#112 Refactor: 아이콘 Wrapper 추가 및 비로그인 유저 이동
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/pages/wishList/wishList.page.tsx
Labels: 🛠️ Refactor

#128 Feat: 회원가입, 로그인, 마이페이지 구현
  src/@types/auth.types.ts
  src/@types/member.types.ts
  src/api/authClient.ts
  src/api/member.ts
  src/components/Auth/AuthInput/AuthInputBox/AuthCurrentPwInputBox.tsx
  src/components/Auth/AuthInput/AuthInputBox/AuthEmailInputBox.tsx
  src/components/Auth/AuthInput/AuthInputBox/AuthInputItem/AuthInput.tsx
  src/components/Auth/AuthInput/AuthInputBox/AuthPwInputBox.tsx
  src/components/Auth/AuthInput/AuthInputBox/index.ts
  src/components/Auth/AuthSurvey/AuthSurvey.tsx
  src/components/Auth/AuthSurvey/AuthSurveyOption.tsx
  src/components/Auth/Login/LoginForm.tsx
  src/components/Auth/index.ts
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/components/Mypage/EditPassword/EditPwForm.tsx
  src/components/Mypage/LogoutButton.tsx
  src/components/Mypage/MypageInfo.tsx
  src/components/Mypage/MypageItem.tsx
  src/components/Mypage/MypageList.tsx
  src/components/common/BackBox/BackBox.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/nav/Nav.tsx
  src/hooks/useGetUserInfo.ts
  src/pages/mypage/editPassword.page.tsx
  src/pages/mypage/editUserInfo.page.tsx
  src/pages/mypage/editUserSurvey.page.tsx
  src/pages/mypage/index.ts
  src/pages/mypage/mypage.page.tsx
  src/pages/signup/signupSuccess.page.tsx
  src/pages/signup/signupSurvey.page.tsx
  src/recoil/Auth.atom.ts
  src/router/mainRouter.tsx
  src/router/routerLayout.tsx
  src/utils/localStorageFun.ts
  src/utils/survey.constants.ts
Labels: ✨ Feature

#118 Refactor: Page 최소 높이 설정
  src/api/tours.ts
  src/components/Wish/Wish.tsx
  src/components/Wish/WishItem.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/like/Like.tsx
Labels: 🛠️ Refactor

#129 Env: 2차스프린트 배포
  src/@types/auth.types.ts
  src/@types/member.types.ts
  src/api/authClient.ts
  src/api/member.ts
  src/api/tours.ts
  src/components/Auth/AuthInput/AuthInputBox/AuthCurrentPwInputBox.tsx
  src/components/Auth/AuthInput/AuthInputBox/AuthEmailInputBox.tsx
  src/components/Auth/AuthInput/AuthInputBox/AuthInputItem/AuthInput.tsx
  src/components/Auth/AuthInput/AuthInputBox/AuthPwInputBox.tsx
  src/components/Auth/AuthInput/AuthInputBox/index.ts
  src/components/Auth/AuthSurvey/AuthSurvey.tsx
  src/components/Auth/AuthSurvey/AuthSurveyOption.tsx
  src/components/Auth/Login/LoginForm.tsx
  src/components/Auth/index.ts
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/components/Mypage/EditPassword/EditPwForm.tsx
  src/components/Mypage/LogoutButton.tsx
  src/components/Mypage/MypageInfo.tsx
  src/components/Mypage/MypageItem.tsx
  src/components/Mypage/MypageList.tsx
  src/components/Wish/Wish.tsx
  src/components/Wish/WishItem.tsx
  src/components/common/BackBox/BackBox.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/like/Like.tsx
  src/components/common/nav/Nav.tsx
  src/hooks/useGetUserInfo.ts
  src/pages/mypage/editPassword.page.tsx
  src/pages/mypage/editUserInfo.page.tsx
  src/pages/mypage/editUserSurvey.page.tsx
  src/pages/mypage/index.ts
  src/pages/mypage/mypage.page.tsx
  src/pages/signup/signupSuccess.page.tsx
  src/pages/signup/signupSurvey.page.tsx
  src/recoil/Auth.atom.ts
  src/router/mainRouter.tsx
  src/router/routerLayout.tsx
  src/utils/localStorageFun.ts
  src/utils/survey.constants.ts
Labels: 🌏 Deploy

#130 Refactor: wishlist url 변경 및 mypage 클릭시 active
  src/components/DetailSectionTop/DetailTopButton.tsx
  src/components/DetailSectionTop/index.tsx
  src/components/Mypage/MypageList.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/nav/Nav.tsx
  src/pages/detail/detail.page.tsx
  src/router/mainRouter.tsx
Labels: 🛠️ Refactor

#137 Fix: 댓글 유저 권한적용
  src/api/comments.ts
  src/api/review.ts
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/Review/CommentItem.tsx
  src/components/Review/ReviewComments.tsx
Labels: 👾 Fix

#139 Feat: 소켓연결 명세
  package.json
  pnpm-lock.yaml
  src/@types/auth.types.ts
  src/@types/member.types.ts
  src/api/authClient.ts
  src/api/member.ts
  src/api/socket.ts
  src/api/tours.ts
  src/components/Auth/AuthInput/AuthInputBox/AuthCurrentPwInputBox.tsx
  src/components/Auth/AuthInput/AuthInputBox/AuthEmailInputBox.tsx
  src/components/Auth/AuthInput/AuthInputBox/AuthInputItem/AuthInput.tsx
  src/components/Auth/AuthInput/AuthInputBox/AuthPwInputBox.tsx
  src/components/Auth/AuthInput/AuthInputBox/index.ts
  src/components/Auth/AuthSurvey/AuthSurvey.tsx
  src/components/Auth/AuthSurvey/AuthSurveyOption.tsx
  src/components/Auth/Login/LoginForm.tsx
  src/components/Auth/index.ts
  src/components/DetailSectionBottom/DetailReviews.tsx
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/components/Mypage/EditPassword/EditPwForm.tsx
  src/components/Mypage/LogoutButton.tsx
  src/components/Mypage/MypageInfo.tsx
  src/components/Mypage/MypageItem.tsx
  src/components/Mypage/MypageList.tsx
  src/components/Review/ReviewButton.tsx
  src/components/Review/ReviewKeyword.tsx
  src/components/Review/ReviewPosting.tsx
  src/components/Wish/Wish.tsx
  src/components/Wish/WishItem.tsx
  src/components/common/BackBox/BackBox.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/button/Button.tsx
  src/components/common/header/DetailHeader.tsx
  src/components/common/header/ReviewHeader.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/like/Like.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/children/DeleteAlert.tsx
  src/components/common/nav/Nav.tsx
  src/components/common/toastpopup/ToastPopUp.tsx
  src/hooks/useGetUserInfo.ts
  src/pages/main/main.page.tsx
  src/pages/mypage/editPassword.page.tsx
  src/pages/mypage/editUserInfo.page.tsx
  src/pages/mypage/editUserSurvey.page.tsx
  src/pages/mypage/index.ts
  src/pages/mypage/mypage.page.tsx
  src/pages/signup/signupSuccess.page.tsx
  src/pages/signup/signupSurvey.page.tsx
  src/recoil/Auth.atom.ts
  src/router/mainRouter.tsx
  src/router/routerLayout.tsx
  src/utils/localStorageFun.ts
  src/utils/socket.ts
  src/utils/survey.constants.ts
Labels: ✨ Feature

#138 Fix: 리프레시 저장 문제 해결
  src/api/authClient.ts
  src/api/client.ts
  src/components/Mypage/DeleteMemberButton.tsx
  src/components/common/BackBox/BackBox.tsx
  src/pages/mypage/editUserInfo.page.tsx
Labels: 👾 Fix

#140 Fe 79 feat/mypage review
  src/components/Review/ReviewComments.tsx
  src/components/common/nav/InputComment.tsx
  src/pages/detail/detail.page.tsx
  src/pages/reviewComment/reviewComment.page.tsx
Labels: 👾 Fix

#146 Env: 2차 스프린트 2차배포
  src/@types/auth.types.ts
  src/@types/member.types.ts
  src/api/authClient.ts
  src/api/client.ts
  src/components/Auth/AuthSurvey/AuthSurvey.tsx
  src/components/Auth/Login/AuthButtons/KakaoLoginButton.tsx
  src/components/Auth/Login/KakaoLogin.tsx
  src/components/Auth/Login/LoginForm.tsx
  src/components/Auth/Login/index.ts
  src/components/DetailSectionBottom/DetailReviews.tsx
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/DetailSectionTop/DetailToursButtons.tsx
  src/components/Mypage/DeleteMemberButton.tsx
  src/components/Mypage/EditPassword/EditPwForm.tsx
  src/components/Mypage/LogoutButton.tsx
  src/components/Mypage/MypageItem.tsx
  src/components/Mypage/MypageList.tsx
  src/components/Review/CommentItem.tsx
  src/components/Review/DetailReview.tsx
  src/components/Review/MyReview.tsx
  src/components/Review/ReviewComments.tsx
  src/components/common/BackBox/BackBox.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/modal/children/EditDelete.tsx
  src/components/common/modal/children/MyAlert.tsx
  src/components/common/nav/InputComment.tsx
  src/pages/login/login.page.tsx
  src/pages/login/loginKakao.page.tsx
  src/pages/mypage/editPassword.page.tsx
  src/pages/mypage/editUserInfo.page.tsx
  src/pages/mypage/editUserSurvey.page.tsx
  src/pages/signup/signup.page.tsx
  src/pages/signup/signupInfo.page.tsx
  src/recoil/modal.ts
Labels: 🌏 Deploy

#150 Tabs 컴포넌트 생성
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/socket.ts
  src/components/Tours/ToursList.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/Wish/WishList.tsx
  src/components/common/nav/Nav.tsx
  src/components/common/tab/Tab.tsx
  src/pages/main/main.page.tsx
  src/pages/plan/planPlaceSearch.page.tsx
  src/pages/plan/planPlaceTrip.page.tsx
  src/pages/plan/planTrip.page.tsx
  src/pages/trip/trip.page.tsx
  src/router/socketRouter.tsx
  src/utils/socket.ts
Labels: ✨ Feature

#152 Feat: 나의 여정 마크업 및 API 연동 완료
  src/@types/trips.types.ts
  src/api/member.ts
  src/components/DetailSectionTop/DetailTopButton.tsx
  src/components/MyTrip/MyTrip.tsx
  src/components/MyTrip/MyTripItem.tsx
  src/components/MyTrip/MyTripList.tsx
  src/components/Wish/WishItem.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/nav/Nav.tsx
  src/pages/detail/detail.page.tsx
  src/pages/myTrip/myTrip.page.tsx
  src/router/mainRouter.tsx
Labels: ✨ Feature

#156 QA / 닉네임 수정 기능 구현
  src/@types/auth.types.ts
  src/@types/member.types.ts
  src/assets/images/defaultProfileImg.svg
  src/components/Auth/AuthInput/AuthInputBox/AuthCurrentPwInputBox.tsx
  src/components/Auth/AuthInput/AuthInputBox/AuthNicknameInputBox.tsx
  src/components/Auth/SignupInfo/SignupInfoForm.tsx
  src/components/Auth/SignupInfo/UserInfoImg.tsx
  src/components/Mypage/UserInfoForm.tsx
  src/pages/mypage/editUserInfo.page.tsx
  src/pages/signup/signupInfo.page.tsx
Labels: ✨ Feature, 🛠️ Refactor

#159 Fe 85 feat/our trip prefer
  src/components/Review/ReviewComments.tsx
  src/components/Trip/TripPreference.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/common/modal/children/EditDelete.tsx
  src/components/common/nav/InputComment.tsx
  src/recoil/review.ts
  src/router/routerLayout.tsx
  src/utils/calculatePercentage.ts
  tailwind.config.js
Labels: ✨ Feature, 📬 API, 🎨 Publishing, 🛠️ Refactor

#161 Refactor: 로그인 판별 localstorage에서 api response로 변경
  src/components/DetailSectionTop/DetailToursButtons.tsx
  src/components/common/nav/InputComment.tsx
Labels: 🛠️ Refactor

#157 Feat: 여행 생성 페이지 마크업
  package.json
  pnpm-lock.yaml
  src/components/DatePicker/Calendar.tsx
  src/components/Tours/CreateTripButton.tsx
  src/components/common/header/BackHeader.tsx
  src/components/common/icons/Icons.tsx
  src/components/createTrip/InputField.tsx
  src/components/createTrip/SelectDate.tsx
  src/components/createTrip/SelectDestination.tsx
  src/components/search/ResultCategory.tsx
  src/components/search/SearchInput.tsx
  src/components/search/SearchRegion.tsx
  src/index.css
  src/pages/create/createTrip.page.tsx
  src/recoil/tripDate.ts
  src/router/mainRouter.tsx
  src/router/routerLayout.tsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 Publishing

#163 Refactor: 빌드 에러 및 여정 생성 버튼
  src/@types/trips.types.ts
  src/components/MyTrip/CreateMyTripButton.tsx
  src/components/MyTrip/MyTrip.tsx
  src/components/MyTrip/MyTripItem.tsx
  src/components/MyTrip/MyTripList.tsx
  src/components/Wish/Wish.tsx
  src/pages/myTrip/myTrip.page.tsx
Labels: 👾 Fix, 🛠️ Refactor

#162 Feat: 소켓 명세 및 추상화
  src/@types/auth.types.ts
  src/@types/member.types.ts
  src/@types/service.ts
  src/@types/socket.types.ts
  src/api/socket.ts
  src/assets/images/defaultProfileImg.svg
  src/components/Auth/AuthInput/AuthInputBox/AuthCurrentPwInputBox.tsx
  src/components/Auth/AuthInput/AuthInputBox/AuthNicknameInputBox.tsx
  src/components/Auth/SignupInfo/SignupInfoForm.tsx
  src/components/Auth/SignupInfo/UserInfoImg.tsx
  src/components/DetailSectionTop/DetailTopButton.tsx
  src/components/Mypage/UserInfoForm.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Review/ReviewComments.tsx
  src/components/Trip/TripPreference.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/modal/children/EditDelete.tsx
  src/components/common/nav/InputComment.tsx
  src/pages/detail/detail.page.tsx
  src/pages/mypage/editUserInfo.page.tsx
  src/pages/signup/signupInfo.page.tsx
  src/recoil/review.ts
  src/router/routerLayout.tsx
  src/utils/calculatePercentage.ts
  src/utils/socket.ts
  tailwind.config.js
Labels: ✨ Feature

#151 QA/닉네임수정, Design/여정페이지 마크업
  package.json
  pnpm-lock.yaml
  src/@types/auth.types.ts
  src/@types/member.types.ts
  src/@types/trips.types.ts
  src/api/member.ts
  src/api/socket.ts
  src/assets/images/defaultProfileImg.svg
  src/components/Auth/AuthInput/AuthInputBox/AuthCurrentPwInputBox.tsx
  src/components/Auth/AuthInput/AuthInputBox/AuthNicknameInputBox.tsx
  src/components/Auth/SignupInfo/SignupInfoForm.tsx
  src/components/Auth/SignupInfo/UserInfoImg.tsx
  src/components/DatePicker/Calendar.tsx
  src/components/DetailSectionTop/DetailTopButton.tsx
  src/components/DetailSectionTop/DetailToursButtons.tsx
  src/components/MyTrip/CreateMyTripButton.tsx
  src/components/MyTrip/MyTrip.tsx
  src/components/MyTrip/MyTripItem.tsx
  src/components/MyTrip/MyTripList.tsx
  src/components/Mypage/MypageList.tsx
  src/components/Mypage/UserInfoForm.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Plan/TripBudget.tsx
  src/components/Review/ReviewComments.tsx
  src/components/Tours/CreateTripButton.tsx
  src/components/Trip/PlanTripButton.tsx
  src/components/Trip/TripInfo.tsx
  src/components/Trip/TripPreference.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/Wish/Wish.tsx
  src/components/Wish/WishItem.tsx
  src/components/common/BackBox/BackBox.tsx
  src/components/common/header/BackHeader.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/modal/children/EditDelete.tsx
  src/components/common/nav/InputComment.tsx
  src/components/common/nav/Nav.tsx
  src/components/common/tab/Tab.tsx
  src/components/createTrip/InputField.tsx
  src/components/createTrip/SelectDate.tsx
  src/components/createTrip/SelectDestination.tsx
  src/components/search/ResultCategory.tsx
  src/components/search/SearchInput.tsx
  src/components/search/SearchRegion.tsx
  src/index.css
  src/pages/create/createTrip.page.tsx
  src/pages/detail/detail.page.tsx
  src/pages/myTrip/myTrip.page.tsx
  src/pages/mypage/editUserInfo.page.tsx
  src/pages/plan/planTrip.page.tsx
  src/pages/signup/signupInfo.page.tsx
  src/pages/trip/trip.page.tsx
  src/recoil/review.ts
  src/recoil/tripDate.ts
  src/router/mainRouter.tsx
  src/router/routerLayout.tsx
  src/router/socketRouter.tsx
  src/utils/calculatePercentage.ts
  src/utils/socket.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Publishing, 🛠️ Refactor

#166 여정페이지 커스텀훅 구현
  src/@types/service.ts
  src/@types/socket.types.ts
  src/api/socket.ts
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/common/icons/Icons.tsx
  src/hooks/useSocket.ts
  src/pages/main/main.page.tsx
  src/recoil/socket.ts
  src/router/socketRouter.tsx
  src/utils/socket.ts
Labels: 🌏 Deploy

#164 나의 여정 생성 api 연동 완료
  src/@types/trips.types.ts
  src/api/member.ts
  src/api/trips.ts
  src/components/DatePicker/Calendar.tsx
  src/hooks/useCounter.ts
  src/pages/create/createTrip.page.tsx
  src/utils/formatDate.ts
Labels: ✨ Feature, 📬 API, 🛠️ Refactor

#168 2차 QA배포
  src/@types/auth.types.ts
  src/@types/service.ts
  src/@types/socket.types.ts
  src/@types/trips.types.ts
  src/api/member.ts
  src/api/socket.ts
  src/api/trips.ts
  src/components/Auth/AuthSurvey/AuthSurvey.tsx
  src/components/Auth/AuthSurvey/AuthSurveyOption.tsx
  src/components/DatePicker/Calendar.tsx
  src/components/Mypage/LogoutButton.tsx
  src/components/Mypage/MypageItem.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/common/icons/Icons.tsx
  src/hooks/useCounter.ts
  src/hooks/useSocket.ts
  src/pages/create/createTrip.page.tsx
  src/pages/main/main.page.tsx
  src/pages/signup/signup.page.tsx
  src/recoil/socket.ts
  src/router/socketRouter.tsx
  src/utils/formatDate.ts
  src/utils/socket.ts
Labels: 🌏 Deploy

#171 Feat: 여정목록조회 페이지 신규 마크업 및 기능 구현 완료
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/@types/trips.types.ts
  src/api/member.ts
  src/api/trips.ts
  src/components/MyTrip/CreateMyTripButton.tsx
  src/components/MyTrip/MyTrip.tsx
  src/components/MyTrip/MyTripAfterList.tsx
  src/components/MyTrip/MyTripBeforeList.tsx
  src/components/MyTrip/MyTripIngItem.tsx
  src/components/MyTrip/MyTripIngList.tsx
  src/components/MyTrip/MyTripItem.tsx
  src/components/MyTrip/MyTripList.tsx
  src/components/common/modal/Modal.tsx
  src/utils/calculateTripDuration.ts
Labels: ✨ Feature, 🎨 Publishing

#174 Feat: 소켓 명세 변경사항 반영
  src/@types/socket.types.ts
  src/api/socket.ts
  src/recoil/socket.ts
Labels: 📬 API

#176 Fix: 소켓 api 변경사항 적용
  src/@types/service.ts
  src/@types/socket.types.ts
  src/api/socket.ts
  src/components/Plan/PlanItemBox.tsx
  src/recoil/socket.ts
Labels: 📬 API

#177 여정 생성 페이지 완료
  src/components/DatePicker/Calendar.tsx
  src/components/Tours/CreateTripButton.tsx
  src/components/Tours/ToursCategoryItem.tsx
  src/components/Trip/LikedToursList.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/common/icons/Icons.tsx
  src/components/createTrip/SelectDate.tsx
  src/components/createTrip/SelectDestination.tsx
  src/components/search/SearchResult.tsx
  src/pages/create/createTrip.page.tsx
Labels: ✨ Feature, 📬 API, 🛠️ Refactor

#182 Feat: 지도 위치 재설정
  src/components/DatePicker/Calendar.tsx
  src/components/Plan/TripBudget.tsx
  src/components/Plan/TripMap.tsx
  src/components/Tours/CreateTripButton.tsx
  src/components/Tours/ToursCategoryItem.tsx
  src/components/Trip/LikedToursList.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/tab/Tab.tsx
  src/components/createTrip/SelectDate.tsx
  src/components/createTrip/SelectDestination.tsx
  src/components/search/SearchResult.tsx
  src/pages/create/createTrip.page.tsx
Labels: ✨ Feature

#183 Feat: 소켓연결 중간배포
  package-lock.json
  src/@types/service.ts
  src/@types/socket.types.ts
  src/api/socket.ts
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Plan/TripBudget.tsx
  src/components/Plan/TripMap.tsx
  src/components/common/header/ReviewHeader.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/tab/Tab.tsx
  src/hooks/useSocket.ts
  src/router/socketRouter.tsx
  src/utils/utils.ts
Labels: 🌏 Deploy

#185 Chore: 여졍페이지 충돌 해결
  src/components/Plan/PlanItem.tsx
  src/components/Plan/TripMap.tsx
  src/components/Trip/TripInfo.tsx
  src/hooks/useSocket.ts
Labels: 🧹 Chore

#186 Chore: 여졍페이지 충돌 해결
  src/components/Plan/PlanItem.tsx
  src/components/Plan/TripMap.tsx
  src/components/Trip/TripInfo.tsx
  src/hooks/useSocket.ts
Labels: 🧹 Chore

#189 Fe 88 feat/connected trip members
  src/api/trips.ts
  src/components/Trip/PlanTripButton.tsx
  src/components/Trip/TripInfo.tsx
  src/components/Trip/TripParticipant.tsx
  src/components/Trip/TripPreference.tsx
  src/components/common/accordion/Accordion.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/children/TripSurveyMember.tsx
  src/components/common/nav/InputComment.tsx
  src/recoil/trip.ts
  tailwind.config.js
Labels: ✨ Feature, 📬 API, 🎨 Publishing

#187 Fe 69 feat/create/where when
  src/api/trips.ts
  src/components/common/button/ListSelectBtn.tsx
  src/pages/plan/OurLikedList.tsx
  src/pages/plan/addPlace/AddtoListBtn.tsx
  src/pages/plan/addPlace/MyLiked.tsx
  src/pages/plan/addPlace/MyLikedList.tsx
  src/pages/plan/addPlace/MyLikedListItem.tsx
  src/pages/plan/addPlace/PlanAddPlace.page.tsx
  src/pages/plan/addPlace/ResultCategoryPlan.tsx
  src/pages/plan/addPlace/ResultItem.tsx
  src/pages/plan/addPlace/SearchResult.tsx
  src/pages/plan/planPlaceTrip.page.tsx
  src/pages/trip/AddOurList.tsx
  src/recoil/listItem.ts
  src/router/socketRouter.tsx
Labels: ✨ Feature, 📬 API, 🎨 Publishing

#191 Feat: 여정페이지 여정아이템 순서변경(드래그앤드롭), 삭제, 날짜이동 구현
  package.json
  pnpm-lock.yaml
  src/@types/service.ts
  src/@types/socket.types.ts
  src/api/socket.ts
  src/api/trips.ts
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/PlanMoveItem.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Trip/PlanTripButton.tsx
  src/components/Trip/TripInfo.tsx
  src/components/Trip/TripParticipant.tsx
  src/components/Trip/TripPreference.tsx
  src/components/common/accordion/Accordion.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/button/ListSelectBtn.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/children/TripSurveyMember.tsx
  src/components/common/nav/InputComment.tsx
  src/components/common/toastpopup/ToastPopUp.tsx
  src/pages/plan/OurLikedList.tsx
  src/pages/plan/addPlace/AddtoListBtn.tsx
  src/pages/plan/addPlace/MyLiked.tsx
  src/pages/plan/addPlace/MyLikedList.tsx
  src/pages/plan/addPlace/MyLikedListItem.tsx
  src/pages/plan/addPlace/PlanAddPlace.page.tsx
  src/pages/plan/addPlace/ResultCategoryPlan.tsx
  src/pages/plan/addPlace/ResultItem.tsx
  src/pages/plan/addPlace/SearchResult.tsx
  src/pages/plan/planPlaceTrip.page.tsx
  src/pages/trip/AddOurList.tsx
  src/recoil/listItem.ts
  src/recoil/plan.ts
  src/recoil/trip.ts
  src/router/socketRouter.tsx
  src/utils/utils.ts
  tailwind.config.js
Labels: ✨ Feature

#192 여행 경비 수정 모달, 맵 마커
  src/assets/images/FifthMarker.png
  src/assets/images/FifthSelectedMarker.png
  src/assets/images/FirstMarker.png
  src/assets/images/FirstSelectedMarker.png
  src/assets/images/FourthMarker.png
  src/assets/images/FourthSelectedMarker.png
  src/assets/images/SecondMarker.png
  src/assets/images/SecondSelectedMarker.png
  src/assets/images/ThirdMarker.png
  src/assets/images/ThirdSelectedMarker.png
  src/components/Plan/TripBudget.tsx
  src/components/Plan/TripMap.tsx
  src/components/common/alert/Alert.tsx
Labels: ✨ Feature, 🎨 Publishing

#193 Env: 여정페이지 기능구현 배포
  package.json
  pnpm-lock.yaml
  src/@types/service.ts
  src/@types/socket.types.ts
  src/api/socket.ts
  src/assets/images/FifthMarker.png
  src/assets/images/FifthSelectedMarker.png
  src/assets/images/FirstMarker.png
  src/assets/images/FirstSelectedMarker.png
  src/assets/images/FourthMarker.png
  src/assets/images/FourthSelectedMarker.png
  src/assets/images/SecondMarker.png
  src/assets/images/SecondSelectedMarker.png
  src/assets/images/ThirdMarker.png
  src/assets/images/ThirdSelectedMarker.png
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/PlanMoveItem.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Plan/TripBudget.tsx
  src/components/Plan/TripMap.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/toastpopup/ToastPopUp.tsx
  src/recoil/plan.ts
  src/utils/utils.ts
Labels: 🌏 Deploy

#194 Env: 여정페이지 기능 구현 배포
  package.json
  pnpm-lock.yaml
  src/@types/service.ts
  src/@types/socket.types.ts
  src/api/socket.ts
  src/assets/images/FifthMarker.png
  src/assets/images/FifthSelectedMarker.png
  src/assets/images/FirstMarker.png
  src/assets/images/FirstSelectedMarker.png
  src/assets/images/FourthMarker.png
  src/assets/images/FourthSelectedMarker.png
  src/assets/images/SecondMarker.png
  src/assets/images/SecondSelectedMarker.png
  src/assets/images/ThirdMarker.png
  src/assets/images/ThirdSelectedMarker.png
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/PlanMoveItem.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Plan/TripBudget.tsx
  src/components/Plan/TripMap.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/toastpopup/ToastPopUp.tsx
  src/recoil/plan.ts
  src/utils/utils.ts
Labels: 🌏 Deploy

#195 Alert 컴포넌트 수정
  src/components/common/alert/Alert.tsx
Labels: 🎨 Publishing

#196 Alert 컴포넌트 수정
  src/components/common/alert/Alert.tsx
Labels: 🎨 Publishing

#201 Feat: 권한확인 커스텀훅 구현
  src/@types/socket.types.ts
  src/@types/trips.types.ts
  src/api/socket.ts
  src/api/trips.ts
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanMoveItem.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/common/tab/Tab.tsx
  src/hooks/useGetTripsAuthority.ts
  src/hooks/useSocket.ts
  src/recoil/plan.ts
  src/recoil/socket.ts
  src/router/socketRouter.tsx
Labels: ✨ Feature

#198 Feat: 우리의 관심 여행지 조회
  src/@types/trips.types.ts
  src/api/trips.ts
  src/components/DetailSectionTop/DetailTopButton.tsx
  src/components/DetailSectionTop/DetailToursRating.tsx
  src/components/Trip/LikedToursList.tsx
  src/components/Trip/LikedToursLists/LikedToursListBox.tsx
  src/components/Trip/LikedToursLists/LikedToursListCategory.tsx
  src/components/Trip/LikedToursLists/LikedToursListCategoryItem.tsx
  src/components/Trip/LikedToursLists/LikedToursListItem.tsx
  src/components/Wish/WishItem.tsx
  src/components/common/icons/Icons.tsx
  src/pages/detail/detail.page.tsx
  src/recoil/review.ts
Labels: ✨ Feature

#203 경비 수정 적용, 탭 컴포넌트 패딩 제거
  src/@types/socket.types.ts
  src/@types/trips.types.ts
  src/api/socket.ts
  src/api/trips.ts
  src/components/DetailSectionTop/DetailTopButton.tsx
  src/components/DetailSectionTop/DetailToursRating.tsx
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanMoveItem.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Plan/TripBudget.tsx
  src/components/Plan/TripMap.tsx
  src/components/Trip/LikedToursList.tsx
  src/components/Trip/LikedToursLists/LikedToursListBox.tsx
  src/components/Trip/LikedToursLists/LikedToursListCategory.tsx
  src/components/Trip/LikedToursLists/LikedToursListCategoryItem.tsx
  src/components/Trip/LikedToursLists/LikedToursListItem.tsx
  src/components/Trip/PlanTripButton.tsx
  src/components/Trip/TripInfo.tsx
  src/components/Trip/TripParticipant.tsx
  src/components/Trip/TripPreference.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/Wish/WishItem.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/tab/Tab.tsx
  src/hooks/useGetTripsAuthority.ts
  src/hooks/useSocket.ts
  src/pages/detail/detail.page.tsx
  src/recoil/plan.ts
  src/recoil/review.ts
  src/recoil/socket.ts
  src/router/socketRouter.tsx
Labels: ✨ Feature, 🎨 Publishing

#200 Fe 88 feat/connected trip members
  src/@types/service.ts
  src/@types/socket.types.ts
  src/components/Plan/PlanSectionTop.tsx
  src/components/Review/CommentItem.tsx
  src/components/Trip/PlanTripButton.tsx
  src/components/Trip/TripInfo.tsx
  src/components/Trip/TripParticipant.tsx
  src/components/Trip/TripPreference.tsx
  src/components/Trip/TripRealtimeEditor.tsx
  src/components/Trip/TripSchedule.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/children/MyAlert.tsx
  src/hooks/useSocket.ts
Labels: ✨ Feature, 📬 API, 👾 Fix

#202 Style: 세부 디자인 수정
  src/components/MyTrip/MyTripItem.tsx
  src/components/Trip/LikedToursLists/LikedToursListItem.tsx
  src/components/common/icons/Icons.tsx
Labels: 🎨 Publishing

#205 Feat: 권한에따른 ui 조건부 렌더링 구현
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanMoveItem.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/common/tab/Tab.tsx
Labels: ✨ Feature

#204 Feat: 여정 경비 수정, Design: Tab 컴포넌트 수정
  src/components/Plan/PlanItem.tsx
  src/components/Plan/TripBudget.tsx
  src/components/Plan/TripMap.tsx
  src/components/Trip/LikedToursList.tsx
  src/components/Trip/TripParticipant.tsx
  src/components/Trip/TripPreference.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/tab/Tab.tsx
Labels: ✨ Feature, 🎨 Publishing

#209 Feat: 맵마커 클릭 시 변경
  src/components/Plan/TripMap.tsx
Labels: ✨ Feature, 🎨 Publishing

#212 계획 정보 소켓 연결
  src/components/Plan/PlanSchedule.tsx
  src/components/Plan/PlanSectionTop.tsx
Labels: ✨ Feature, 📬 API

#207 Feat: 맵 마커 적용
  src/assets/images/FifthMarker.png
  src/assets/images/FifthSelectedMarker.png
  src/assets/images/FirstMarker.png
  src/assets/images/FirstSelectedMarker.png
  src/assets/images/FourthMarker.png
  src/assets/images/FourthSelectedMarker.png
  src/assets/images/SecondMarker.png
  src/assets/images/SecondSelectedMarker.png
  src/assets/images/ThirdMarker.png
  src/assets/images/ThirdSelectedMarker.png
  src/components/Plan/PlanSchedule.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Plan/TripBudget.tsx
  src/components/Plan/TripMap.tsx
  src/components/Trip/TripRealtimeEditor.tsx
  src/components/Trip/TripSchedule.tsx
  src/components/common/icons/Icons.tsx
  src/utils/getColor.ts
Labels: ✨ Feature, 🎨 Publishing, 👾 Fix

#210 우리의 관심목록 추가
  src/@types/tours.types.ts
  src/api/socket.ts
  src/api/trips.ts
  src/components/Plan/PlanSectionTop.tsx
  src/components/common/button/ListSelectBtn.tsx
  src/pages/plan/AddToTripPlan/OurLiked.tsx
  src/pages/plan/AddToTripPlan/OurLikedList.tsx
  src/pages/plan/AddToTripPlan/OurLikedListItem.tsx
  src/pages/plan/OurLikedList.tsx
  src/pages/plan/addPlace/AddtoListBtn.tsx
  src/pages/plan/addToOurPlace/AddtoListBtn.tsx
  src/pages/plan/addToOurPlace/MyLiked.tsx
  src/pages/plan/addToOurPlace/MyLikedList.tsx
  src/pages/plan/addToOurPlace/MyLikedListItem.tsx
  src/pages/plan/addToOurPlace/PlanAddPlace.page.tsx
  src/pages/plan/addToOurPlace/ResultCategoryPlan.tsx
  src/pages/plan/addToOurPlace/ResultItem.tsx
  src/pages/plan/addToOurPlace/SearchResult.tsx
  src/pages/search/search.page.tsx
  src/pages/trip/AddOurList.page.tsx
  src/router/routerLayout.tsx
  src/router/socketRouter.tsx
  src/utils/getTripIdFromUrl.ts
Labels: ✨ Feature, 📬 API, 🛠️ Refactor

#208 Feat: 공유 기능 구현
  package.json
  pnpm-lock.yaml
  src/api/trips.ts
  src/components/Auth/Login/LoginForm.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Share/CodeInput.tsx
  src/components/Share/CopyBox.tsx
  src/components/Share/CopyToast.tsx
  src/components/Share/IsEditableModal.tsx
  src/components/Trip/EditCodeModal.tsx
  src/components/Trip/TripSchedule.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/common/BackBox/BackBox.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/icons/Icons.tsx
  src/pages/share/share.page.tsx
  src/pages/share/shareCode.page.tsx
  src/router/socketRouter.tsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 Publishing

#211 Feat: 여정페이지 리펙토링
  src/@types/service.ts
  src/api/trips.ts
  src/components/DetailSectionBottom/DetailReviewStats.tsx
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Trip/TripInfo.tsx
  src/components/Trip/TripPreference.tsx
  src/components/Trip/TripRealtimeEditor.tsx
  src/components/Trip/TripSchedule.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/common/icons/Icons.tsx
  src/hooks/useGetMyTrips.ts
  src/hooks/useGetTrips.ts
  src/hooks/useGetTripsAuthority.ts
  src/hooks/useSocket.ts
  src/recoil/socket.ts
  src/router/socketRouter.tsx
  src/utils/utils.ts
Labels: 🛠️ Refactor

#213 Refactor: 여정페이지 리펙토링
  src/@types/service.ts
  src/@types/socket.types.ts
  src/@types/trips.types.ts
  src/api/socket.ts
  src/api/trips.ts
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/MyTrip/MyTripItem.tsx
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanMoveItem.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Plan/TripBudget.tsx
  src/components/Trip/EditCodeModal.tsx
  src/components/Trip/LikedToursList.tsx
  src/components/Trip/LikedToursLists/LikedToursListBox.tsx
  src/components/Trip/LikedToursLists/LikedToursListItem.tsx
  src/components/Trip/TripRealtimeEditor.tsx
  src/components/Trip/TripSchedule.tsx
  src/components/Trip/TripSectionTop.tsx
  src/hooks/useGetTripsAuthority.ts
  src/hooks/useSocket.ts
  src/pages/plan/AddToTripPlan/OurLiked.tsx
  src/pages/plan/addToOurPlace/AddtoListBtn.tsx
  src/pages/plan/addToOurPlace/MyLiked.tsx
  src/pages/plan/addToOurPlace/SearchResult.tsx
  src/pages/share/shareCode.page.tsx
  src/pages/trip/AddOurList.page.tsx
  src/recoil/socket.ts
  src/router/socketRouter.tsx
Labels: 🛠️ Refactor

#216 Feat: 여정 수정 및 삭제
  src/@types/trips.types.ts
  src/api/trips.ts
  src/components/Plan/TripBudget.tsx
  src/components/Trip/EditCodeModal.tsx
  src/components/Trip/TripSchedule.tsx
  src/components/common/tab/Tab.tsx
  src/components/common/toastpopup/ToastPopUp.tsx
  src/hooks/useCounter.ts
  src/pages/plan/AddToTripPlan/OurLiked.tsx
  src/pages/plan/addToOurPlace/AddtoListBtn.tsx
  src/pages/plan/addToOurPlace/PlanAddPlace.page.tsx
  src/pages/plan/addToOurPlace/ResultCategoryPlan.tsx
  src/pages/plan/addToOurPlace/SearchResult.tsx
  src/pages/trip/tripEdit.page.tsx
  src/router/socketRouter.tsx
Labels: ✨ Feature, 📬 API, 🎨 Publishing, 👾 Fix

#214 Feat: 상품가격 수정 구현
  src/@types/socket.types.ts
  src/api/socket.ts
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/TripBudget.tsx
  src/hooks/useSocket.ts
Labels: ✨ Feature

#218 Feat: 내 여행취향 설정하러가기 구현
  src/components/Plan/PlanItemBox.tsx
  src/components/Trip/TripPreference.tsx
  src/pages/mypage/editUserSurvey.page.tsx
Labels: 👾 Fix

#220 여정 지도 default 설정
  src/components/Plan/PlanSchedule.tsx
  src/components/Plan/TripMap.tsx
  src/components/Trip/EditCodeModal.tsx
Labels: 🛠️ Refactor

#221 Fix: 여행취향 디폴트 디자인 구현 및 디버깅
  src/components/Plan/PlanSectionTop.tsx
  src/components/Trip/TripPreference.tsx
  src/components/Trip/TripRealtimeMember.tsx
  src/components/common/tab/Tab.tsx
  src/utils/calculatePercentage.ts
Labels: 👾 Fix

#219 Fix: 여정아이템 toLocaleString 적용
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/PlanSchedule.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Plan/TripMap.tsx
  src/components/Trip/EditCodeModal.tsx
  src/components/Trip/TripPreference.tsx
  src/components/Trip/TripRealtimeMember.tsx
  src/components/common/tab/Tab.tsx
  src/utils/calculatePercentage.ts
Labels: 👾 Fix

#222 Fix: '40대' 오류 수정 / 버튼 태그 중복 해결
  src/@types/member.types.ts
  src/components/Share/IsEditableModal.tsx
  src/components/Trip/EditCodeModal.tsx
  src/components/common/icons/Icons.tsx
  src/utils/authSelectOptions.ts
Labels: 🎨 Publishing, 👾 Fix

#225 QA: 여정페이지 / 메인페이지 디자인
  src/components/Plan/TripBudget.tsx
  src/components/Tours/ToursCategory.tsx
  src/components/Tours/ToursCategoryItem.tsx
  src/components/Tours/ToursCategoryItemSkeleton.tsx
  src/components/Tours/ToursItem.tsx
  src/components/Trip/EditCodeModal.tsx
  src/components/common/nav/Nav.tsx
  src/components/common/tab/Tab.tsx
  src/pages/trip/tripEdit.page.tsx
Labels: 🎨 Publishing, 👾 Fix

#229 여정 나가기 텍스트 변경
  src/components/Trip/EditCodeModal.tsx
Labels: 🎨 Publishing

#230 Feat: 일정 추가하기 구현
  src/api/trips.ts
  src/components/DetailSectionBottom/DetailReviews.tsx
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/DetailSectionTop/DetailSectionTop.tsx
  src/components/DetailSectionTop/DetailToursRating.tsx
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/PlanMoveItem.tsx
  src/components/Tours/ToursCategory.tsx
  src/components/Trip/TripInfo.tsx
  src/components/common/accordion/Accordion.tsx
  src/components/common/icons/Icons.tsx
  src/hooks/useGetMyTrips.ts
  src/hooks/useSocket.ts
  src/pages/plan/addToOurPlace/AddtoListBtn.tsx
Labels: ✨ Feature

#231 Feat: 일정 추가하기 구현
  src/api/trips.ts
  src/components/DetailSectionBottom/DetailReviews.tsx
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/DetailSectionTop/DetailSectionTop.tsx
  src/components/DetailSectionTop/DetailToursRating.tsx
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/PlanMoveItem.tsx
  src/components/Tours/ToursCategory.tsx
  src/components/Trip/TripInfo.tsx
  src/components/common/accordion/Accordion.tsx
  src/components/common/icons/Icons.tsx
  src/hooks/useGetMyTrips.ts
  src/hooks/useSocket.ts
  src/pages/plan/addToOurPlace/AddtoListBtn.tsx
Labels: ✨ Feature

#233 Chore: msw관련 코드 제거
  public/mockServiceWorker.js
  src/components/DetailSectionBottom/DetailReviewStats.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/create/createTrip.page.tsx
  src/router/routerLayout.tsx
Labels: 🧹 Chore

#234 Refactor: 여정 QA 적용
  src/components/Auth/AuthSurvey/AuthSurvey.tsx
  src/components/Share/IsEditableModal.tsx
  src/pages/mypage/editUserSurvey.page.tsx
Labels: 🛠️ Refactor

#236 Design: 여정 편집 모달 width 수정
  src/components/Trip/EditCodeModal.tsx
  src/components/Trip/TripInfo.tsx
Labels: 🎨 Publishing

#240 여정 수정 페이지 QA 반영
  src/pages/trip/tripEdit.page.tsx
Labels: 🎨 Publishing, 👾 Fix

#242 Fe 100 feat/design qa
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/Review/CommentItem.tsx
  src/components/Review/ReviewButton.tsx
  src/components/Review/ReviewComments.tsx
  src/components/Review/ReviewPosting.tsx
  src/components/common/header/DetailHeader.tsx
  src/components/common/header/ReviewHeader.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/children/EditDelete.tsx
  src/components/common/modal/children/MyAlert.tsx
Labels: 🛠️ Refactor

#243 여행 아이템 모달 수정
  src/components/Plan/PlanItemBox.tsx
Labels: 🎨 Publishing

#250 QA: 우리의관심여행지 - 투표 취소 기능 추가
  src/components/Trip/LikedToursLists/LikedToursListItem.tsx
Labels: ✨ Feature, 🛠️ Refactor

#252 ScrollTopButton / 여행페이지 Nav 추가
  src/components/Plan/PlanSectionTop.tsx
  src/components/Plan/ScrollTopButton.tsx
  src/components/Review/MyReview.tsx
  src/components/Share/IsEditableModal.tsx
  src/components/Trip/EditCodeModal.tsx
  src/components/Trip/LikedToursList.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/Wish/Wish.tsx
  src/components/search/SearchResult.tsx
  src/router/routerLayout.tsx
Labels: ✨ Feature, 🎨 Publishing

#253 투표 취소 기능 / ScrollToTop 버튼 추가
  src/components/Plan/PlanSectionTop.tsx
  src/components/Plan/ScrollTopButton.tsx
  src/components/Review/MyReview.tsx
  src/components/Review/ReviewButton.tsx
  src/components/Review/ReviewPosting.tsx
  src/components/Review/ReviewRating.tsx
  src/components/Share/IsEditableModal.tsx
  src/components/Trip/EditCodeModal.tsx
  src/components/Trip/LikedToursList.tsx
  src/components/Trip/LikedToursLists/LikedToursListItem.tsx
  src/components/Trip/PlanTripButton.tsx
  src/components/Trip/TripPreference.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/Wish/Wish.tsx
  src/components/common/header/DetailHeader.tsx
  src/components/common/header/ReviewHeader.tsx
  src/components/search/SearchResult.tsx
  src/router/routerLayout.tsx
Labels: ✨ Feature, 🎨 Publishing

#254 경로 시간 포맷팅 추가
  src/components/Plan/PlanItemBox.tsx
Labels: ✨ Feature, 🎨 Publishing

#255 경로 시간 포맷팅 추가
  src/components/Plan/PlanItemBox.tsx
Labels: ✨ Feature, 🎨 Publishing

#256 여정 수정페이지 nav 제거
  src/router/routerLayout.tsx
Labels: 🎨 Publishing, 👾 Fix

#257 여정 수정페이지 nav 제거
  src/router/routerLayout.tsx
Labels: 🎨 Publishing, 👾 Fix

#267 디자인 QA / 워딩 변경
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Review/MyReview.tsx
  src/components/Tours/ToursList.tsx
  src/components/Trip/EditCodeModal.tsx
  src/components/Trip/PlanTripButton.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/Wish/Wish.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/scrollTopButton/ScrollTopButton.tsx
  src/components/common/toastpopup/ToastPopUp.tsx
  src/components/search/SearchResult.tsx
Labels: 🎨 Publishing

#268 디자인 QA / 워딩 변경
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Review/MyReview.tsx
  src/components/Tours/ToursList.tsx
  src/components/Trip/EditCodeModal.tsx
  src/components/Trip/PlanTripButton.tsx
  src/components/Trip/TripSectionTop.tsx
  src/components/Wish/Wish.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/scrollTopButton/ScrollTopButton.tsx
  src/components/common/toastpopup/ToastPopUp.tsx
  src/components/search/SearchResult.tsx
Labels: 🎨 Publishing

#269 Fe 103 feat/refactor/1st
  src/@types/review.types.ts
  src/@types/tours.types.ts
  src/@types/trips.types.ts
  src/App.tsx
  src/api/review.ts
  src/components/DetailSectionBottom/DetailReviews.tsx
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/Review/CommentItem.tsx
  src/components/Review/MyReview.tsx
  src/components/Review/Review.tsx
  src/components/Review/ReviewComments.tsx
  src/components/Review/ReviewKeyword.tsx
  src/components/Tours/ToursCategory.tsx
  src/components/Tours/ToursCategoryItem.tsx
  src/components/Tours/ToursItem.tsx
  src/components/Tours/ToursList.tsx
  src/components/Wish/WishItem.tsx
  src/components/Wish/WishList.tsx
  src/components/common/nav/InputComment.tsx
  src/components/search/ResultCategory.tsx
  src/components/search/ResultItem.tsx
  src/hooks/useReviewStats.ts
  src/hooks/useReviewStatsCalculator.ts
  src/pages/plan/AddToTripPlan/OurLikedList.tsx
  src/pages/plan/AddToTripPlan/OurLikedListItem.tsx
  src/pages/plan/addToOurPlace/MyLikedList.tsx
  src/pages/plan/addToOurPlace/MyLikedListItem.tsx
  src/pages/plan/addToOurPlace/ResultCategoryPlan.tsx
  src/pages/plan/addToOurPlace/ResultItem.tsx
  src/recoil/review.ts
  src/recoil/trip.ts
  src/styles/globalStyles.ts
  src/styles/theme.ts
Labels: 👾 Fix, 🛠️ Refactor

#270 Fe 102 feat/refactor
  src/@types/review.types.ts
  src/@types/tours.types.ts
  src/@types/trips.types.ts
  src/App.tsx
  src/api/review.ts
  src/components/DetailSectionBottom/DetailReviews.tsx
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/Review/CommentItem.tsx
  src/components/Review/MyReview.tsx
  src/components/Review/Review.tsx
  src/components/Review/ReviewComments.tsx
  src/components/Review/ReviewKeyword.tsx
  src/components/Tours/ToursCategory.tsx
  src/components/Tours/ToursCategoryItem.tsx
  src/components/Tours/ToursItem.tsx
  src/components/Tours/ToursList.tsx
  src/components/Wish/WishItem.tsx
  src/components/Wish/WishList.tsx
  src/components/common/nav/InputComment.tsx
  src/components/search/ResultCategory.tsx
  src/components/search/ResultItem.tsx
  src/hooks/useReviewStats.ts
  src/hooks/useReviewStatsCalculator.ts
  src/pages/plan/AddToTripPlan/OurLikedList.tsx
  src/pages/plan/AddToTripPlan/OurLikedListItem.tsx
  src/pages/plan/addToOurPlace/MyLikedList.tsx
  src/pages/plan/addToOurPlace/MyLikedListItem.tsx
  src/pages/plan/addToOurPlace/ResultCategoryPlan.tsx
  src/pages/plan/addToOurPlace/ResultItem.tsx
  src/recoil/review.ts
  src/recoil/trip.ts
  src/styles/globalStyles.ts
  src/styles/theme.ts
Labels: 👾 Fix, 🛠️ Refactor

#274 Docs: Readme 초안 작성
  README.md
  image.png
Labels: 📝 Docs

#272 QA 반영 및 상세 수정
  src/components/Tours/CreateTripButton.tsx
  src/components/addToList/AddToTripPlan/OurLiked.tsx
  src/components/addToList/AddToTripPlan/OurLikedList.tsx
  src/components/addToList/AddToTripPlan/OurLikedListItem.tsx
  src/components/addToList/addToOurPlace/AddtoListBtn.tsx
  src/components/addToList/addToOurPlace/MyLiked.tsx
  src/components/addToList/addToOurPlace/MyLikedList.tsx
  src/components/addToList/addToOurPlace/MyLikedListItem.tsx
  src/components/addToList/addToOurPlace/PlanAddPlace.page.tsx
  src/components/addToList/addToOurPlace/ResultCategoryPlan.tsx
  src/components/addToList/addToOurPlace/ResultItem.tsx
  src/components/addToList/addToOurPlace/SearchResult.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/toggleGroup/ToggleValue.tsx
  src/components/search/RegionSelect.tsx
  src/components/search/ResultItem.tsx
  src/components/search/SearchInput.tsx
  src/components/search/StartSearchBtn.tsx
  src/constants.ts
  src/pages/create/createTrip.page.tsx
  src/pages/trip/AddOurList.page.tsx
  src/router/socketRouter.tsx
Labels: 👾 Fix, 🛠️ Refactor, 🧹 Chore

#271 QA: 여정페이지, 상세페이지 기능 및 디자인 일부 수정
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/DetailSectionTop/DetailToursButtons.tsx
  src/components/DetailSectionTop/DetailToursInfo.tsx
  src/components/DetailSectionTop/DetailToursMap.tsx
  src/components/DetailSectionTop/DetailToursRating.tsx
  src/components/MyTrip/MyTrip.tsx
  src/components/MyTrip/MyTripAfterList.tsx
  src/components/MyTrip/MyTripBeforeList.tsx
  src/components/MyTrip/MyTripIngItem.tsx
  src/components/MyTrip/MyTripItem.tsx
  src/components/Trip/LikedToursList.tsx
  src/components/Trip/LikedToursLists/LikedToursListCategory.tsx
  src/components/Trip/LikedToursLists/LikedToursListCategoryItem.tsx
  src/components/Trip/LikedToursLists/LikedToursListItem.tsx
  src/components/Wish/Wish.tsx
  src/components/Wish/WishCategory.tsx
  src/components/Wish/WishCategoryItem.tsx
  src/components/Wish/WishItem.tsx
  src/components/common/header/DetailHeader.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/like/Like.tsx
  src/components/common/nav/Nav.tsx
  src/components/common/noData/NoDataMessage.tsx
Labels: 🎨 Publishing, 🛠️ Refactor

#275 Refator: 소켓 최적화(소켓새로고침 최적화, 디바운싱, 쓰로틀링), 커서공유 구현
  package.json
  pnpm-lock.yaml
  src/@types/service.ts
  src/@types/socket.types.ts
  src/api/socket.ts
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/Plan/PlanCursor.tsx
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanMoveItem.tsx
  src/components/Plan/PlanOtherCursor.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Plan/TripBudget.tsx
  src/hooks/useSocket.ts
Labels: ✨ Feature, 🛠️ Refactor

#277 Style: 아이템 디자인 수정
  src/components/Trip/LikedToursLists/LikedToursListItem.tsx
  src/components/Wish/WishItem.tsx
Labels: 🎨 Publishing

#276 Refator: 소켓 최적화(소켓새로고침 최적화, 디바운싱, 쓰로틀링), 커서공유 구현
  package.json
  pnpm-lock.yaml
  src/@types/service.ts
  src/@types/socket.types.ts
  src/api/socket.ts
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/Plan/PlanCursor.tsx
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/PlanMoveItem.tsx
  src/components/Plan/PlanOtherCursor.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/Plan/TripBudget.tsx
  src/components/Trip/LikedToursLists/LikedToursListItem.tsx
  src/components/Wish/WishItem.tsx
  src/hooks/useSocket.ts
Labels: ✨ Feature, 🛠️ Refactor

#278 Feat: 디바운싱 재적용, 모바일환경에서 커서공유 블락
  package.json
  pnpm-lock.yaml
  src/api/socket.ts
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanSectionTop.tsx
Labels: ✨ Feature

#281 Fix: 나의 여정 간격 수정
  src/components/MyTrip/MyTripIngItem.tsx
  src/components/MyTrip/MyTripItem.tsx
  src/components/common/nav/Nav.tsx
Labels: 🎨 Publishing, 👾 Fix

#280 Fix: Tab, Nav 간격 수정
  src/components/common/nav/Nav.tsx
  src/components/common/tab/Tab.tsx
Labels: 🎨 Publishing, 👾 Fix

#279 Fix: 글자수제한 19->16, 이런점이좋았어요 세로가운데정렬 적용
  package.json
  pnpm-lock.yaml
  src/api/socket.ts
  src/components/DetailSectionBottom/DetailReviewStats.tsx
  src/components/DetailSectionTop/DetailAddSchedule.tsx
  src/components/MyTrip/MyTripIngItem.tsx
  src/components/MyTrip/MyTripItem.tsx
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanItem.tsx
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/PlanSectionTop.tsx
  src/components/common/nav/Nav.tsx
  src/components/common/tab/Tab.tsx
Labels: 👾 Fix

#282 Fix : 여정, 관심목록 조회 페이지 QA 반영
  src/components/MyTrip/MyTrip.tsx
  src/components/MyTrip/MyTripAfterList.tsx
  src/components/MyTrip/MyTripBeforeList.tsx
  src/components/MyTrip/MyTripIngItem.tsx
  src/components/MyTrip/MyTripIngList.tsx
  src/components/MyTrip/MyTripItem.tsx
  src/components/Trip/LikedToursList.tsx
  src/components/Trip/LikedToursLists/LikedToursListBox.tsx
  src/components/Trip/LikedToursLists/LikedToursListCategory.tsx
  src/components/Trip/LikedToursLists/LikedToursListCategoryItem.tsx
  src/components/Trip/LikedToursLists/LikedToursListItem.tsx
  src/components/Wish/Wish.tsx
  src/components/Wish/WishCategoryItem.tsx
  src/components/Wish/WishItem.tsx
  src/components/Wish/WishList.tsx
Labels: 🎨 Publishing, 🛠️ Refactor

#284 디자인 2차 QA
  src/components/DetailSectionBottom/ReviewItem.tsx
  src/components/Review/CommentItem.tsx
  src/components/Review/ReviewComments.tsx
  src/components/Review/ReviewKeyword.tsx
  src/components/common/nav/InputComment.tsx
Labels: 🎨 Publishing, 🛠️ Refactor

#285 Refactor: 마이페이지 디자인 QA 적용
  src/components/Auth/AuthInput/AuthInputBox/AuthInputItem/AuthInput.tsx
  src/components/Auth/AuthSurvey/AuthSurvey.tsx
  src/components/Auth/SignupInfo/AuthDropDown/AuthDropDown.tsx
  src/components/Auth/SignupInfo/AuthDropDown/AuthDropDownOption.tsx
  src/components/Auth/SignupInfo/SignupInfoForm.tsx
  src/components/Mypage/UserInfoForm.tsx
  src/components/common/BackBox/BackBox.tsx
  src/components/common/icons/Icons.tsx
  src/pages/mypage/editUserInfo.page.tsx
  src/pages/mypage/editUserSurvey.page.tsx
  src/pages/signup/signup.page.tsx
  src/pages/signup/signupSuccess.page.tsx
  src/pages/signup/signupSurvey.page.tsx
  src/utils/authSelectOptions.ts
Labels: 🎨 Publishing, 🛠️ Refactor

#287 디자인 QA 최종
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/TripBudget.tsx
  src/components/Tours/ToursCategoryItem.tsx
  src/components/Trip/LikedToursLists/LikedToursListCategoryItem.tsx
  src/components/Trip/TripPreference.tsx
  src/components/Wish/WishCategoryItem.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/nav/Nav.tsx
  src/components/common/tab/Tab.tsx
  src/components/common/toastpopup/ToastPopUp.tsx
  src/pages/create/createTrip.page.tsx
  src/pages/plan/planPlaceSearch.page.tsx
  src/pages/trip/tripEdit.page.tsx
  src/router/socketRouter.tsx
Labels: 🎨 Publishing, 👾 Fix

#288 디자인 QA
  src/components/Plan/PlanItemBox.tsx
  src/components/Plan/TripBudget.tsx
  src/components/Tours/ToursCategoryItem.tsx
  src/components/Trip/LikedToursLists/LikedToursListCategoryItem.tsx
  src/components/Trip/TripPreference.tsx
  src/components/Wish/WishCategoryItem.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/nav/Nav.tsx
  src/components/common/tab/Tab.tsx
  src/components/common/toastpopup/ToastPopUp.tsx
  src/pages/create/createTrip.page.tsx
  src/pages/plan/planPlaceSearch.page.tsx
  src/pages/trip/tripEdit.page.tsx
  src/router/socketRouter.tsx
Labels: 🎨 Publishing, 👾 Fix

#289 장소 추가 시 해당 Day 탭 유지
  src/components/Plan/PlanSectionTop.tsx
  src/components/Trip/PlanTripButton.tsx
  src/components/Trip/TripPreference.tsx
  src/components/addToList/addToOurPlace/AddtoListBtn.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/tab/Tab.tsx
  src/recoil/plan.ts
  src/utils/utils.ts
Labels: ✨ Feature, 👾 Fix

#290 장소 추가 시 해당 Day 탭 유지
  src/components/Plan/PlanSectionTop.tsx
  src/components/Trip/PlanTripButton.tsx
  src/components/Trip/TripPreference.tsx
  src/components/addToList/addToOurPlace/AddtoListBtn.tsx
  src/components/common/icons/Icons.tsx
  src/components/common/tab/Tab.tsx
  src/recoil/plan.ts
  src/utils/utils.ts
Labels: ✨ Feature, 👾 Fix

#291 Fix: 디자인 qa 반영
  src/components/Plan/PlanEditItemBox.tsx
  src/components/Plan/PlanMoveItem.tsx
Labels: 👾 Fix

#296 이연수 리드미
  README.md
Labels: 📝 Docs

#297 Fe 104 feat/readme
  README.md
  image-1.png
  image-2.png
  image.png
Labels: 📝 Docs

#298 Docs: 리드미 작성
  README.md
  image-1.png
  image-2.png
  image.png
Labels: 📝 Docs

#299 공유 뒤로가기 시 지도 에러 해결
  src/components/Plan/PlanSectionTop.tsx
  src/pages/share/share.page.tsx
Labels: 👾 Fix

#300 공유 뒤로가기 클릭 시 에러 해결
  src/components/Plan/PlanSectionTop.tsx
  src/pages/share/share.page.tsx
Labels: 👾 Fix
